#!/bin/sh
rm *.pyc */*.pyc
echo 'pylint,'
. `dirname $0`/ENV/bin/activate
pylint --rcfile=.pylint *.py bbs
echo 'pychecker,'
pychecker -F .pycheckrc blessings.py db.py engine.py terminal.py telnet.py bbs
echo 'compileall,'
python -m compileall -q `dirname $0`
