"""
Default province for Sword of the Samurai.
"""
__author__ = ''
__version__ = '$Id'
__copyright__ = ''
__license__ = ''

defaultProvinces = {
'Satsuma': {'clan': 'Shimazu',
   'honor': 4.0,
   'generalship': 7.0,
   'swordsmanship': 2.0,
   'land': 4.0,
   'neighbors': ['Higo','Hyuga']
   },
'Hyuga': {'clan': 'Takahashi',
   'honor': 3.0,
   'generalship': 5.0,
   'swordsmanship': 5.0,
   'land': 5.0,
   'neighbors': ['Higo','Bungo','Satsuma']
   },
'Higo': {'clan': 'Aso',
   'honor': 4.0,
   'generalship': 5.0,
   'swordsmanship': 6.0,
   'land': 3.0,
   'neighbors': ['Satsuma','Hyuga','Bungo','Hizen']
   },
'Hizen': {'clan': 'Ryuzoji',
   'honor': 4.0,
   'generalship': 2.0,
   'swordsmanship': 5.0,
   'land': 7.0,
   'neighbors': ['Higo','Bungo','Chikuzen']
   },
'Bungo': {'clan': 'Otomo',
   'honor': 5.0,
   'generalship': 6.0,
   'swordsmanship': 5.0,
   'land': 2.0,
   'neighbors': ['Hyuga','Higo','Hizen','Chikuzen','Suwo']
   },
'Chikuzen': {'clan': 'Hosokawa',
   'honor': 6.0,
   'generalship': 4.0,
   'swordsmanship': 3.0,
   'land': 5.0,
   'neighbors': ['Bungo','Hizen','Nagato']
   },
'Nagato': {'clan': 'Naito',
   'honor': 4.0,
   'generalship': 2.0,
   'swordsmanship': 7.0,
   'land': 5.0,
   'neighbors': ['Iwami','Suwo','Chikuzen']
   },
'Suwo': {'clan': 'Ouchi',
   'honor': 7.0,
   'generalship': 2.0,
   'swordsmanship': 2.0,
   'land': 7.0,
   'neighbors': ['Bungo','Nagato','Iwami','Aki']
   },
'Nagato': {'clan': 'Naito',
   'honor': 4.0,
   'generalship': 2.0,
   'swordsmanship': 7.0,
   'land': 5.0,
   'neighbors': ['Chikuzen','Suwo','Iwami']
   },
'Iwami': {'clan': 'Toida',
   'honor': 5.0,
   'generalship': 5.0,
   'swordsmanship': 3.0,
   'land': 5.0,
   'neighbors': ['Aki','Suwo','Nagato','Izumo','Bingo']
   },
'Aki': {'clan': 'Mori',
   'honor': 3.0,
   'generalship': 7.0,
   'swordsmanship': 6.0,
   'land': 2.0,
   'neighbors': ['Iwami','Suwo','Bingo']
   },
'Bingo': {'clan': 'Kobayakawa',
   'honor': 3.0,
   'generalship': 6.0,
   'swordsmanship': 4.0,
   'land': 5.0,
   'neighbors': ['Aki','Iwami','Izumo','Hoki','Bitchu']
   },
'Izumo': {'clan': 'Amako',
   'honor': 4.0,
   'generalship': 2.0,
   'swordsmanship': 5.0,
   'land': 4.0,
   'neighbors': ['Iwami','Bingo','Hoki']
   },
'Bitchu': {'clan': 'Matsuya',
   'honor': 5.0,
   'generalship': 5.0,
   'swordsmanship': 5.0,
   'land': 3.0,
   'neighbors': ['Bingo','Hoki','Mimasaka','Bizen']
   },
'Hoki': {'clan': 'Kikkawa',
   'honor': 5.0,
   'generalship': 3.0,
   'swordsmanship': 4.0,
   'land': 6.0,
   'neighbors': ['Izumo','Bingo','Bitchu','Mimasaka','Inaba']
   },
'Bizen': {'clan': 'Ukita',
   'honor': 3.0,
   'generalship': 6.0,
   'swordsmanship': 6.0,
   'land': 3.0,
   'neighbors': ['Harima','Mimasaka','Bitchu']
   },
'Mimasaka': {'clan': 'Tsuyama',
   'honor': 6.0,
   'generalship': 5.0,
   'swordsmanship': 2.0,
   'land': 5.0,
   'neighbors': ['Bizen','Bitchu','Hoki','Inaba','Harima']
   },
'Inaba': {'clan': 'Yamana',
   'honor': 4.0,
   'generalship': 2.0,
   'swordsmanship': 4.0,
   'land': 5.0,
   'neighbors': ['Hoki','Mimasaka','Tango','Harima']
   },
'Harima': {'clan': 'Ikeda',
   'honor': 7.0,
   'generalship': 4.0,
   'swordsmanship': 3.0,
   'land': 4.0,
   'neighbors': ['Bizen','Mimasaka','Inaba','Tango','Tamba','Settsu']
   },
'Tango': {'clan': 'Ishiki',
   'honor': 2.0,
   'generalship': 3.0,
   'swordsmanship': 7.0,
   'land': 6.0,
   'neighbors': ['Inaba','Harima','Tamba','Omi','Echizen']
   },
'Tamba': {'clan': 'Hatano',
   'honor': 4.0,
   'generalship': 4.0,
   'swordsmanship': 3.0,
   'land': 7.0,
   'neighbors': ['Harima','Tango','Omi','Settsu']
   },
'Settsu': {'clan': 'Toyotomi',
   'honor': 2.0,
   'generalship': 7.0,
   'swordsmanship': 5.0,
   'land': 4.0,
   'neighbors': ['Harima','Tamba','Omi','Izumi']
   },
'Izumi': {'clan': 'Miyoshi',
   'honor': 4.0,
   'generalship': 2.0,
   'swordsmanship': 7.0,
   'land': 4.0,
   'neighbors': ['Sanuki','Kii','Yamato','Omi','Settsu']
   },
'Kii': {'clan': 'Horiuchi',
   'honor': 5.0,
   'generalship': 3.0,
   'swordsmanship': 5.0,
   'land': 5.0,
   'neighbors': ['Izumi','Yamato','Ise','Sanuki']
   },
'Yamato': {'clan': 'Tsutsui',
   'honor': 2.0,
   'generalship': 5.0,
   'swordsmanship': 6.0,
   'land': 5.0,
   'neighbors': ['Kii','Izumi','Omi','Ise']
   },
'Omi': {'clan': 'Asai',
   'honor': 3.0,
   'generalship': 6.0,
   'swordsmanship': 5.0,
   'land': 4.0,
   'neighbors': ['Tango','Echizen','Mino','Ise','Yamato','Izumi','Settsu','Tamba']
   },
'Ise': {'clan': 'Kitabatake',
   'honor': 4.0,
   'generalship': 3.0,
   'swordsmanship': 5.0,
   'land': 6.0,
   'neighbors': ['Kii','Yamato','Omi','Mino']
   },
'Echizen': {'clan': 'Asakura',
   'honor': 6.0,
   'generalship': 6.0,
   'swordsmanship': 3.0,
   'land': 3.0,
   'neighbors': ['Tango','Omi','Mino','Hida','Kaga']
   },
'Mino': {'clan': 'Oda',
   'honor': 3.0,
   'generalship': 7.0,
   'swordsmanship': 6.0,
   'land': 3.0,
   'neighbors': ['Ise','Omi','Echizen','Hida','Shinano','Mikawa']
   },
'Mikawa': {'clan': 'Tokugawa',
   'honor': 7.0,
   'generalship': 7.0,
   'swordsmanship': 2.0,
   'land': 2.0,
   'neighbors': ['Totomi','Shinano','Mino']
   },
'Totomi': {'clan': 'Imagawa',
   'honor': 8.0,
   'generalship': 3.0,
   'swordsmanship': 3.0,
   'land': 4.0,
   'neighbors': ['Mikawa','Shinano','Suruga']
   },
'Shinano': {'clan': 'Murakami',
   'honor': 3.0,
   'generalship': 4.0,
   'swordsmanship': 7.0,
   'land': 3.0,
   'neighbors': ['Totomi','Mikawa','Mino','Hida','Etchu','Echigo','Kozuke','Kai','Suruga']
   },
'Hida': {'clan': 'Ishikawa',
   'honor': 5.0,
   'generalship': 5.0,
   'swordsmanship': 2.0,
   'land': 6.0,
   'neighbors': ['Echizen','Kaga','Etchu','Shinano','Mino']
   },
'Kaga': {'clan': 'Niwa',
   'honor': 5.0,
   'generalship': 4.0,
   'swordsmanship': 6.0,
   'land': 4.0,
   'neighbors': ['Echizen','Hida','Etchu']
   },
'Etchu': {'clan': 'Jinbo',
   'honor': 3.0,
   'generalship': 5.0,
   'swordsmanship': 5.0,
   'land': 5.0,
   'neighbors': ['Kaga','Hida','Shinano','Echigo']
   },
'Shinano': {'clan': 'Murakami',
   'honor': 3.0,
   'generalship': 4.0,
   'swordsmanship': 7.0,
   'land': 4.0,
   'neighbors': ['Totomi','Mikawa','Mino','Hida','Etchu','Echigo','Kozuke','Kai','Suruga']
   },
'Totomi': {'clan': 'Imagawa',
   'honor': 8.0,
   'generalship': 3.0,
   'swordsmanship': 3.0,
   'land': 4.0,
   'neighbors': ['Suruga','Shinano','Mikawa']
   },
'Suruga': {'clan': 'Nakamura',
   'honor': 7.0,
   'generalship': 2.0,
   'swordsmanship': 3.0,
   'land': 6.0,
   'neighbors': ['Izu','Sagami','Kai','Shinano','Totomi']
   },
'Izu': {'clan': 'Kasigi',
   'honor': 2.0,
   'generalship': 5.0,
   'swordsmanship': 8.0,
   'land': 3.0,
   'neighbors': ['Suruga','Sagami']
   },
'Sagami': {'clan': 'Hojo',
   'honor': 2.0,
   'generalship': 7.0,
   'swordsmanship': 6.0,
   'land': 4.0,
   'neighbors': ['Izu','Suruga','Kai','Musashi']
   },
'Kai': {'clan': 'Takeda',
   'honor': 5.0,
   'generalship': 8.0,
   'swordsmanship': 2.0,
   'land': 3.0,
   'neighbors': ['Sagami','Suruga','Shinano','Musashi']
   },
'Musashi': {'clan': 'Miyagi',
   'honor': 3.0,
   'generalship': 3.0,
   'swordsmanship': 6.0,
   'land': 6.0,
   'neighbors': ['Sagami','Kai','Kozuke','Shimosa']
   },
'Kozuke': {'clan': 'Asano',
   'honor': 6.0,
   'generalship': 5.0,
   'swordsmanship': 3.0,
   'land': 4.0,
   'neighbors': ['Shimosa','Musashi','Shinano','Echigo','Mutsu','Hitachi']
   },
'Echigo': {'clan': 'Uesugi',
   'honor': 6.0,
   'generalship': 7.0,
   'swordsmanship': 2.0,
   'land': 3.0,
   'neighbors': ['Etchu','Shinano','Kozuke','Mutsu','Dewa']
   },
'Dewa': {'clan': 'Mogami',
   'honor': 5.0,
   'generalship': 4.0,
   'swordsmanship': 5.0,
   'land': 4.0,
   'neighbors': ['Mutsu','Echigo']
   },
'Mutsu': {'clan': 'Date',
   'honor': 3.0,
   'generalship': 4.0,
   'swordsmanship': 3.0,
   'land': 8.0,
   'neighbors': ['Hitachi','Kozuke','Echigo','Dewa']
   },
'Hitachi': {'clan': 'Satake',
   'honor': 4.0,
   'generalship': 3.0,
   'swordsmanship': 4.0,
   'land': 7.0,
   'neighbors': ['Shimosa','Kozuke','Mutsu']
   },
'Shimosa': {'clan': 'Satomi',
   'honor': 5.0,
   'generalship': 5.0,
   'swordsmanship': 6.0,
   'land': 2.0,
   'neighbors': ['Musashi','Hitachi','Kozuke']
   },
'Iyo': {'clan': 'Todo',
   'honor': 4.0,
   'generalship': 3.0,
   'swordsmanship': 7.0,
   'land': 4.0,
   'neighbors': ['Sanuki','Tosa']
   },
'Tosa': {'clan': 'Shosokabe',
   'honor': 6.0,
   'generalship': 5.0,
   'swordsmanship': 4.0,
   'land': 3.0,
   'neighbors': ['Iyo','Sanuki']
   },
'Sanuki': {'clan': 'Hachisuka',
   'honor': 4.0,
   'generalship': 4.0,
   'swordsmanship': 4.0,
   'land': 6.0,
   'neighbors': ['Iyo','Tosa','Izumi','Kii']
   }
}
